version: '3.8'

services:
  bin-lookup-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge