version: '3.8'

services:
  bin-lookup-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - backend

networks:
  backend:
    external: true